export const ACCOUNT_DEPOSIT = "ACCOUNT_DEPOSIT";
export const ACCOUNT_WITHDRAW = "ACCOUNT_WITHDRAW";
export const ACCOUNT_REQUEST_LOAN = "ACCOUNT_REQUEST_LOAN";
export const ACCOUNT_PAY_LOAN = "ACCOUNT_PAY_LOAN";